require("core.options")
require("core.autocmds")
require("core.keymaps")
require("core.indent")
require("core.scroll")
require("core.buffer")
require("core.rejump")
require("core.terminal")
require("core.statusline")
require("core.format")
require("core.lsp")
-- require("config.nvim.lua.core.lsp")
