return { -- Useful plugin to show you pending keybinds.
  'folke/which-key.nvim',
  event = 'VimEnter', -- Sets the loading event to 'VimEnter'
  opts = {
    preset = 'helix',
    delay = 0,
    icons = {
      mappings = vim.g.have_nerd_font,
      keys = vim.g.have_nerd_font and {} or {
        Up = '<Up> ',
        Down = '<Down> ',
        Left = '<Left> ',
        Right = '<Right> ',
        C = '<C-…> ',
        M = '<M-…> ',
        D = '<D-…> ',
        S = '<S-…> ',
        CR = '<CR> ',
        Esc = '<Esc> ',
        ScrollWheelDown = '<ScrollWheelDown> ',
        ScrollWheelUp = '<ScrollWheelUp> ',
        NL = '<NL> ',
        BS = '<BS> ',
        Space = '<Space> ',
        Tab = '<Tab> ',
        F1 = '<F1>',
        F2 = '<F2>',
        F3 = '<F3>',
        F4 = '<F4>',
        F5 = '<F5>',
        F6 = '<F6>',
        F7 = '<F7>',
        F8 = '<F8>',
        F9 = '<F9>',
        F10 = '<F10>',
        F11 = '<F11>',
        F12 = '<F12>',
      },
    },

    -- Document existing key chains
    spec = {
      { 's', group = ' [S]urround' },
      { '<leader>b', group = '📄[B]uffer' },
      { '<leader>d', group = '🐞[D]ebug' },
      { '<leader>e', group = '❗[E]rror' },
      { '<leader>q', group = '🚪[Q]uit' },
      { '<leader>o', group = '🤖[O]penCode' },
      { '<leader>os', group = '󰋃 [O]penCode [S]ession' },
      { '<leader>op', group = ' [O]penCode [P]ermission' },
      { '<leader>or', group = '󰕌 [O]penCode [R]evert' },
      { '<leader>s', group = '🔎[S]earch' },
    },
  },
}
