#! /bin/sh

chosen=$(printf "Power Off\nReboot\nSuspend" | rofi -dmenu -i -theme-str '@import "powermenu.rasi"')

case "$chosen" in
"Power Off") poweroff ;;
"Reboot") reboot ;;
"Suspend") systemctl suspend ;;
*) exit 1 ;;
esac
